spring:
  application:
    name: gateway
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs, /user-service/swagger-ui/**
          filters:
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}
        - id: user-service-health
          uri: lb://user-service
          predicates:
            - Path=/user-service/health, /user-service/auth/**, /user-service/oauth2/authorization/**, /user-service/login/oauth2/code/**, /user-service/users/announce/*, /user-service/users/announce
          filters:
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - AuthFilter
            - RewritePath=/user-service/(?<remainingPath>.*), /${remainingPath}


        # blog-service
        - id: swagger
          uri: lb://blog-service
          predicates:
            - Path=/blog-service/v3/api-docs, /blog-service/swagger-ui/**
          filters:
            - RewritePath=/blog-service/(?<remainingPath>.*), /${remainingPath}
        - id: health
          uri: lb://blog-service
          predicates:
            - Path=/blog-service/blog/board/userInfo/**, /blog-service/blog/board/search/**, /blog-service/blog/board/nonUser/**, /blog-service/blog/board/article/**, /blog-service/blog/board/all/**, /blog-service/blog/board/list/**
            - Method=GET
          filters:
            - RewritePath=/blog-service/(?<remainingPath>.*), /${remainingPath}
        - id: lock
          uri: lb://blog-service
          predicates:
            - Path=/blog-service/**
          filters:
            - AuthFilter
            - RewritePath=/blog-service/(?<remainingPath>.*), /${remainingPath}


        # code-llm-service
        - id: code-llm-service-swagger
          uri: lb://code-llm-service
          predicates:
            - Path=/code-llm-service/v3/api-docs, /code-llm-service/swagger-ui/**
          filters:
            - RewritePath=/code-llm-service/(?<remainingPath>.*), /${remainingPath}
        - id: code-llm-service
          uri: lb://code-llm-service
          predicates:
            - Path=/code-llm-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-llm-service/(?<remainingPath>.*), /${remainingPath}


        # code-compile-service
        - id: code-compile-service-swagger
          uri: lb://code-compile-service
          predicates:
            - Path=/code-compile-service/v3/api-docs, /code-compile-service/swagger-ui/**
          filters:
            - RewritePath=/code-compile-service/(?<remainingPath>.*), /${remainingPath}
        - id: code-compile-service
          uri: lb://code-compile-service
          predicates:
            - Path=/code-compile-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-compile-service/(?<remainingPath>.*), /${remainingPath}

        # code-bank-service
        - id: code-bank-service-swagger
          uri: lb://code-bank-service
          predicates:
            - Path=/code-bank-service/v3/api-docs, /code-bank-service/swagger-ui/**
          filters:
            - RewritePath=/code-bank-service/(?<remainingPath>.*), /${remainingPath}
        - id: code-bank-service-health
          uri: lb://code-bank-service
          predicates:
            - Path=/code-bank-service/code/lists, /code-bank-service/code/non/lists/*
          filters:
            - RewritePath=/code-bank-service/(?<remainingPath>.*), /${remainingPath}
        - id: code-bank-service
          uri: lb://code-bank-service
          predicates:
            - Path=/code-bank-service/**
          filters:
            - AuthFilter
            - RewritePath=/code-bank-service/(?<remainingPath>.*), /${remainingPath}


        # admin-service
        - id: admin-service-swagger
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/v3/api-docs, /admin-service/swagger-ui/**
          filters:
            - RewritePath=/admin-service/(?<remainingPath>.*), /${remainingPath}
        - id: admin-service-health
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/health, /admin-service/auth/**
          filters:
            - RewritePath=/admin-service/(?<remainingPath>.*), /${remainingPath}
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**
          filters:
            - AuthAdminFilter
            - RewritePath=/admin-service/(?<remainingPath>.*), /${remainingPath}

  jwt:
    secret: ${JWT_SECRET}

server:
  port: 19091

# Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# swagger
springdoc:
  swagger-ui:
    enabled: true
    use-root-path: true
    urls:
      - name: user-service
        url: http://172.16.211.57:19091/user-service/v3/api-docs
      - name: blog-service
        url: http://172.16.211.57:19091/blog-service/v3/api-docs
      - name: code-llm-service
        url: http://172.16.211.57:19091/code-llm-service/v3/api-docs
      - name: code-compile-service
        url: http://172.16.211.57:19091/code-compile-service/v3/api-docs
      - name: code-bank-service
        url: http://172.16.211.57:19091/code-bank-service/v3/api-docs
      - name: admin-service
        url: http://172.16.211.57:19091/admin-service/v3/api-docs

#actuator
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

#log
logging:
  level:
    org.springframework.security: TRACE
